[ipopt]
# Define lower and upper bounds for decision variables
x_l = [1.0, 1.0, 1.0, 1.0]
x_u = [5.0, 5.0, 5.0, 5.0]

# Define lower and upper bounds for constraint functions
g_l = [25.0, 40.0]
g_u = [2e19, 40.0]

# Set the initial condition for the decision variables
x = [1.0, 5.0, 5.0, 1.0]

# Set the indexing style to C-style 
index_style = 0

# IPOPT settings
tol = 3.82e-6
mu_strategy = "adaptive"
output_file = "ipopt.out"
linear_solver = "mumps"
